### ISSUE TITLE
EMU crash: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by syaakov** [cisco-system-traffic-generator/trex-emu#21]
trex-emu crashes sometimes when we run it with kernel mode.

output:

```
./trex-emu -k
Run ZMQ server on [RPC:4500, RX: IPC, TX:IPC]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7c1fae]

goroutine 1 [running]:
emu/core.(*cHTimerBucket).decCount(...)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/timerw.go:130
emu/core.(*CHTimerObj).detach(...)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/timerw.go:176
emu/core.(*cHTimerOneWheel).popEvent(0xc000455780?)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/timerw.go:320 +0x2e
emu/core.(*CNATimerWheel).onTickLevel0(0xc0000b4840)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/timerw.go:423 +0x65
emu/core.(*CNATimerWheel).OnTick(0xc0000b4840, 0x32d070?)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/timerw.go:533 +0x32
emu/core.(*TimerCtx).HandleTicks(0xc00026d5f0)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/timer_ctx.go:113 +0x2e
emu/core.(*CThreadCtx).MainLoop(0xc000324000)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/emu/core/thread_ctx.go:391 +0x185
main.RunCoreZmq(0xc00007e480)
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/cmd/trex-emu.go:183 +0x48c
main.main()
	/tmp/build_838_TRex_Emu_1d2de09906f0266741b2c59c2f9e2c6fa287b809/src/cmd/trex-emu.go:191 +0x1e
```

**Comment by syaakov** [comment]
was solved in [8a77593](https://github.com/cisco-system-traffic-generator/trex-emu/commit/8a77593e7ccc408812b0caa94c0d9341adf6c392)
